### PR TITLE
Add events to logout

### PR DESCRIPTION
**Pull request by abelkuruvilla**

### CODE REVIEW

**Comment by abelseniorly** [comment]
@aarondl Can you please add this?

**Comment by aarondl** [comment]
It's a little out of the blue, can I at least hear what use case this is supporting? As authboss itself has no use for it and the hook system is mostly an internal detail though outside consumers _can_ use it.

**Comment by abelseniorly** [comment]
@aarondl This supports any external events that a consumer has to do on logout, just like login events. In my case some custom actions like sending a mail(cant disclose the actual use case here). Now there is no support to add custom actions on logout.

**Comment by aarondl** [comment]
Merged here: ab5003c

**Pull request closed without merging**
